---

- hosts: all
  roles:
    - zuul-include-vars
    - yum-repos-prepare
    - install-ntp
    - install-docker-daemon
    - role: add-insecure-registry
      new_registry: "{{ contrail_docker_registry }}"
    - role: contrail-publish-dockers
      stable: true
