---
- name: DBG 
  debug:
    msg: "contrail_packaging {{ contrail_packaging | default('') }} "
  ignore_errors: true

- name: DBG2
  debug:
    msg: "contrail_docker_registry {{ contrail_docker_registry }} contrail_version {{ contrail_version }} stable {{ stable }}"
  ignore_errors: true

- name: install required packages
  package:
    name: jq
    state: present
  become: true

- name: check that the target account data file exists
  stat:
    path: "{{ target_account_file_data }}"
  register: stat_result
  delegate_to: localhost

- name: load target account data file
  include_vars:
    file: "{{ target_account_file_data }}"
  when: stat_result.stat.exists == True
  delegate_to: localhost

- name: define containers publish tag as current date 
  set_fact:
    PUBLISH_TAG: "{{ ansible_date_time.date }}"
  when: not stable

- name: define containers publish tag as current date stable
  set_fact:
    PUBLISH_TAG: "{{ ansible_date_time.date }}-stable"
  when: stable

- name: copy publish script to target machine
  copy:
    src: publish.sh
    dest: "{{ ansible_env.HOME }}"
    mode: 0755

- name: options for publishing
  template:
    src: "publish.env.j2"
    dest: "{{ ansible_env.HOME }}/publish.env"

- name: publish containers
  command: ./publish.sh
  become: true
  args:
    chdir: "{{ ansible_env.HOME }}"
